<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MedicationDrug;
use Illuminate\Support\Facades\DB;

class MedicationDrugSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('medication_drugs')->truncate();

        $gastro_intestinal_system = [
            'ALUMINIUM / MAGNESIUM HYDROXIDE AND SIMETHICONE',
            'ALUMINIUM HYDROXIDE',
            'CHARCOAL ACTIVATED',
            'DIMETHYLPOLYSILOXANE',
            'GAVISCON (OR EQUIV)',
            'MAGNESIUM TRISILICATE',
            'MYLANTA (OR EQUIV)',
            'HYOSCINE',
            'MEBEVERINE',
            'OTILONIUM BROMIDE',
            'PEPPERMINT OIL',
            'PROPANTHELINE',
            'BISMUTH SUBSALICYLATE',
            'FAMOTIDINE',
            'MISOPROSTOL',
            'PANTOPRAZOLE',
            'RABEPRAZOLE',
            'SUCRALFATE',
            'DEXLANSOPRAZOLE',
            'ESOMEPRAZOLE',
            'LANSOPRAZOLE',
            'DIOCTAHEDRAL SMECTITE',
            'LOPERAMIDE',
            'RACECADOTRIL',
            'BUDESONIDE',
            'BUDESONIDE (RECTAL)',
            'MESALAZINE',
            'MESALAZINE (SUPP/ENEMA)',
            'PREDNISOLONE (FOAM/ENEMA)',
            'SULPHASALAZINE',
            'ADALIMUMAB',
            'INFLIXIMAB',
            'TOFACITINIB',
            'USTEKINUMAB',
            'VEDOLIZUMAB',
            'AGIOCUR (OR EQUIV)',
            'AGIOLAX (OR EQUIV)',
            'BISACODYL',
            'BISACODYL (SUPP)',
            'DOCUSATE',
            'FLEET (OR EQUIV)',
            'GLYCEROL',
            'LACTULOSE',
            'METAMUCIL (OR EQUIV)',
            'NORMACOL PLUS (OR EQUIV)',
            'PHOSPHO-SODA (OR EQUIV)',
            'PICOPREP (OR EQUIV)',
            'POLYETHYLENE GLYCOL',
            'SENNATOSIDE B',
            'LINACLOTIDE',
            'MACROGOL',
            'ANUSOL (OR EQUIV)',
            'EURORECTAL',
            'FAKTU (OR EQUIV)',
            'GLYCERYL TRINITRATE (RECTAL)',
            'PHENOL IN ALMOND OIL',
            'ULTRAPROCT N (OR EQUIV)'
        ];
        $cardiovascular_system = [
            'DIGOXIN',
            'MILRINONE',
            'AMILORIDE',
            'EPLERENONE',
            'BUMETANIDE',
            'DYAZIDE (OR EQUIV)',
            'FRUSEMIDE',
            'HYDROCHLOROTHIAZIDE',
            'INDAPAMIDE',
            'MANNITOL',
            'MANNITOL + SORBITOL',
            'METOLAZONE',
            'MODURETIC (OR EQUIV)',
            'SPIRONOLACTONE',
            'AMIODARONE',
            'DRONEDARONE',
            'ATROPINE',
            'DISOPYRAMIDE',
            'FLECAINIDE',
            'MEXILETINE',
            'PROCAINAMIDE',
            'PROPAFENONE',
            'QUINIDINE',
            'ATENOLOL',
            'BISOPROLOL',
            'BISOPROLOL + HYDROCHLOROTHIAZIDE',
            'CARVEDILOL',
            'ESMOLOL',
            'LABETALOL',
            'METOPROLOL',
            'NADOLOL',
            'PROPRANOLOL',
            'SOTALOL',
            'CAPTOPRIL',
            'CLONIDINE',
            'ENALAPRIL',
            'ENALAPRILAT',
            'HYDRALAZINE',
            'LISINOPRIL',
            'LOSARTAN',
            'METHYLDOPA',
            'MINOXIDIL',
            'NITROPRUSSIDE DIHYDRATE SODIUM',
            'PERINDOPRIL',
            'PHENOXYBENZAMINE',
            'PHENTOLAMINE',
            'PRAZOSIN',
            'PREDONIUM (OR EQUIV)',
            'RAMIPRIL',
            'TERAZOSIN',
            'AMBRISENTAN',
            'AMLODIPINE + VALSARTAN',
            'BOSENTAN',
            'CANDESARTAN',
            'DOXAZOSIN',
            'ILOPROST',
            'IRBESARTAN',
            'IRBESARTAN + HYDROCHLOROTHIAZIDE',
            'LOSARTAN + HYDROCHLOROTHIAZIDE',
            'MACITENTAN',
            'SACUBITRIL + VALSARTAN',
            'SELEXIPAG',
            'SILDENAFIL (REVATIO)',
            'TELMISARTAN',
            'TELMISARTAN + HYDROCHLOROTHIAZIDE',
            'VALSARTAN',
            'VALSARTAN + HYDROCHLOROTHIAZIDE',
            'RIOCIGUAT',
            'AMLODIPINE',
            'DILTIAZEM',
            'FELODIPINE ER',
            'GLYCERYL TRINITRATE',
            'GLYCERYL TRINITRATE (PATCH)',
            'ISOSORBIDE DINITRATE',
            'ISOSORBIDE MONONITRATE',
            'NICARDIPINE',
            'NICERGOLINE',
            'NIFEDIPINE',
            'NIMODIPINE',
            'VERAPAMIL',
            'CILOSTAZOL',
            'GINKGO BILOBA EXTRACT',
            'IVABRADINE',
            'LERCANIDIPINE',
            'NAFTIDROFURYL OXALATE',
            'OXPENTIFYLLINE',
            'ADRENALINE',
            'DOBUTAMINE',
            'DOPAMINE',
            'EPHEDRINE',
            'ISOPRENALINE',
            'METARAMINOL',
            'MIDODRINE',
            'NORADRENALINE',
            'NOREPINEPHRINE',
            'PHENYLEPHRINE',
            'ARGATROBAN',
            'ENOXAPARIN',
            'EPOPROSTENOL',
            'HEPARIN',
            'NADROPARIN',
            'PROTAMINE SULPHATE',
            'SODIUM CITRATE',
            'TINZAPARIN',
            'WARFARIN',
            'APIXABAN',
            'DABIGATRAN',
            'EDOXABAN',
            'RIVAROXABAN',
            'ASPIRIN',
            'ASPIRIN + GLYCINE',
            'CLOPIDOGREL',
            'EPTIFIBATIDE',
            'PRASUGREL',
            'TICAGRELOR',
            'TENECTEPLASE',
            'UROKINASE',
            'ALTEPLASE',
            'ALIROCUMAB',
            'ATORVASTATIN',
            'CHOLESTYRAMINE',
            'EVOLOCUMAB',
            'EZETIMIBE',
            'FENOFIBRATE',
            'GEMFIBROZIL',
            'INCLISIRAN',
            'ROSUVASTATIN',
            'SIMVASTATIN'
        ];
        $respiratory_system = [
            'AMINOPHYLLINE',
            'COMBIVENT (OR EQUIV)',
            'IPRATROPIUM',
            'SALBUTAMOL',
            'SALBUTAMOL (INH)',
            'TERBUTALINE',
            'THEOPHYLLINE',
            'ACLIDINIUM',
            'ACLIDINIUM + FORMOTEROL',
            'GLYCOPYRRONIUM (INH)',
            'INDACATEROL',
            'INDACATEROL + GLYCOPYRRONIUM',
            'OLODATEROL',
            'SALMETEROL',
            'TERBUTALINE (INH)',
            'TIOTROPIUM',
            'TIOTROPIUM + OLODATEROL',
            'UMECLIDINIUM',
            'UMECLIDINIUM + VILANTEROL',
            'BECLOMETHASONE DIPROPIONATE',
            'BUDESONIDE (INH)',
            'BUDESONIDE + FORMOTEROL',
            'CICLESONIDE',
            'ENERZAIR (OR EQUIV)',
            'FLUTICASONE + SALMETEROL',
            'FLUTICASONE PROPIONATE (INH)',
            'FLUTICASONE + FORMOTEROL',
            'FLUTICASONE + VILANTEROL',
            'INDACATEROL + MOMETASONE',
            'TRELEGY (OR EQUIV)',
            'MONTELUKAST',
            'ROFLUMILAST',
            'ACTIFED (OR EQUIV)',
            'ACTIFED COMPOUND (OR EQUIV)',
            'ADRENALINE',
            'CETIRIZINE',
            'CHLORPHENIRAMINE',
            'CYPROHEPTADINE',
            'DESLORATADINE',
            'DEXCHLORPHENIRAMINE',
            'DIPHENHYDRAMINE',
            'EPINEPHRINE',
            'HYDROXYZINE',
            'LORATADINE',
            'PROMETHAZINE',
            'CETIRIZINE + PSEUDOEPHEDRINE',
            'FEXOFENADINE',
            'FEXOFENADINE + PSEUDOEPHEDRINE',
            'LORATADINE + PSEUDOEPHEDRINE',
            'BENRALIZUMAB',
            'DUPILUMAB',
            'MEPOLIZUMAB',
            'OMALIZUMAB',
            'ICATIBANT',
            'BERACTANT',
            'PORACTANT ALFA',
            'ACETYLCYSTEINE',
            'AMBROXOL',
            'BROMHEXINE',
            'CYCLIDROL',
            'BENZOIN COMPOUND TINCTURE',
            'AMMONIA AND IPECACUANHA',
            'COCILLANA (OR EQUIV)',
            'CODEINE PHOSPHATE',
            'DIPHENHYDRAMINE COMPOUND',
            'PHOLCODINE',
            'PROMETHAZINE COMPOUND',
            'PSEUDOEPHEDRINE',
            'NINTEDANIB (OFEV)',
            'CAFFEINE',
            'LYSOZYME',
            'TALC STERILE'
        ];
        $central_nervous_system = [
            'ALPRAZOLAM',
            'BROMAZEPAM',
            'BUSPIRONE',
            'CHLORAL HYDRATE',
            'CHLORDIAZEPOXIDE',
            'CHLORMETHIAZOLE',
            'DIAZEPAM',
            'FLUNITRAZEPAM',
            'LORAZEPAM',
            'MELATONIN',
            'MIDAZOLAM',
            'NITRAZEPAM',
            'TRIAZOLAM',
            'ZOLPIDEM',
            'ZOPICLONE',
            'AMISULPRIDE',
            'ARIPIPRAZOLE',
            'BREXPIPRAZOLE',
            'CHLORPROMAZINE',
            'FLUPENTHIXOL',
            'FLUPHENAZINE',
            'HALOPERIDOL',
            'LITHIUM CARBONATE',
            'LITHIUM SULPHATE',
            'LURASIDONE',
            'OLANZAPINE',
            'PALIPERIDONE',
            'PERICYAZINE',
            'PIMOZIDE',
            'QUETIAPINE',
            'RISPERIDONE',
            'SULPIRIDE',
            'TRIFLUOPERAZINE',
            'ZIPRASIDONE',
            'ZUCLOPENTHIXOL',
            'CLOZAPINE',
            'AMITRIPTYLINE',
            'CITALOPRAM',
            'CLOMIPRAMINE',
            'DEANXIT (OR EQUIV)',
            'DOTHIEPIN',
            'DOXEPIN',
            'FLUOXETINE',
            'IMIPRAMINE',
            'MIANSERIN',
            'MIRTAZAPINE',
            'MOCLOBEMIDE',
            'NORTRIPTYLINE',
            'PAROXETINE',
            'SERTRALINE',
            'TRAZODONE',
            'TRIMIPRAMINE',
            'AGOMELATINE',
            'BUPROPION',
            'DESVENLAFAXINE',
            'DULOXETINE',
            'ESCITALOPRAM',
            'FLUVOXAMINE',
            'MILNACIPRAN',
            'VENLAFAXINE',
            'VORTIOXETINE',
            'BETAHISTINE',
            'CINNARIZINE',
            'DIMENHYDRINATE',
            'DIMENHYDRINATE (SUPP)',
            'DOMPERIDONE',
            'FLUNARIZINE',
            'HYOSCINE (PATCH)',
            'METOCLOPRAMIDE',
            'PROCHLORPERAZINE',
            'PROMETHAZINE',
            'APREPITANT',
            'FOSAPREPITANT',
            'GRANISETRON',
            'NETUPITANT + PALONOSETRON',
            'ONDANSETRON',
            'ALCOHOL ABSOLUTE (INJECTION)',
            'ASPIRIN',
            'BUPRENORPHINE',
            'CAFERGOT (OR EQUIV)',
            'CARBAMAZEPINE',
            'CLONIDINE',
            'CODEINE PHOSPHATE',
            'DIHYDROCODEINE',
            'METHADONE',
            'MORPHINE',
            'PARACETAMOL',
            'PARACETAMOL (SUPP)',
            'PETHIDINE',
            'PIZOTIFEN',
            'SUMATRIPTAN',
            'TRAMADOL',
            'BUPRENORPHINE (PATCH)',
            'FENTANYL (PATCH)',
            'GABAPENTIN',
            'OXYCODONE',
            'PREGABALIN',
            'ZOLMITRIPTAN',
            'ERENUMAB',
            'GALCANEZUMAB',
            'CLOBAZAM',
            'CLONAZEPAM',
            'DIAZEPAM (RECTAL)',
            'ETHOSUXIMIDE',
            'PARALDEHYDE',
            'PHENOBARBITONE',
            'PHENYTOIN',
            'VALPROATE SODIUM',
            'BRIVARACETAM',
            'LACOSAMIDE',
            'LAMOTRIGINE',
            'LEVETIRACETAM',
            'OXCARBAZEPINE',
            'PERAMPANEL',
            'RUFINAMIDE',
            'TOPIRAMATE',
            'VIGABATRIN',
            'AMANTADINE',
            'BENZHEXOL',
            'BENZTROPINE',
            'BROMOCRIPTINE',
            'ENTACAPONE',
            'MADOPAR (OR EQUIV)',
            'PIRACETAM',
            'SELEGILINE',
            'SINEMET (OR EQUIV)',
            'STALEVO (OR EQUIV)',
            'TETRABENAZINE',
            'BOTULINUM TYPE A TOXIN',
            'PRAMIPEXOLE',
            'RASAGILINE',
            'ROPINIROLE',
            'ROTIGOTINE',
            'DISULFIRAM',
            'NALTREXONE',
            'BUPRENORPHINE + NALOXONE',
            'NICOTINE',
            'NICOTINE (PATCH)',
            'VARENICLINE',
            'DONEPEZIL',
            'MEMANTINE',
            'RIVASTIGMINE',
            'GALANTAMINE',
            'RIVASTIGMINE (PATCH)',
            'PYRITINOL'
        ];
        $nutritions_and_blood = [
            'CYANOCOBALAMIN',
            'DESFERRIOXAMINE',
            'FERRIC CARBOXYMALTOSE',
            'FERRIC SACCHARATE',
            'FERROUS SULPHATE',
            'FERRUM HAUSMANN',
            'FOLIC ACID',
            'HYDROXOCOBALAMIN',
            'IRON + VITAMIN C',
            'IRON ISOMALTOSIDE',
            'MECOBALAMIN',
            'ANAGRELIDE',
            'DARBEPOETIN ALFA',
            'DEFERASIROX',
            'DEFERIPRONE',
            'ERYTHROPOIETIN BETA',
            'FILGRASTIM',
            'METHOXY POLYETHYLENE',
            'GLYCOL-EPOETIN BETA',
            'PEGFILGRASTIM',
            'ELTROMBOPAG',
            'PLERIXAFOR',
            'CALCIUM CARBONATE',
            'CALCIUM CHLORIDE DIHYDRATE',
            'CALCIUM GLUCONATE',
            'MAGNESIUM (L-LACTATE DIHYDRATE)',
            'MAGNESIUM SULPHATE',
            'PHOSPHATE',
            'POTASSIUM PHOSPHATE',
            'SELENIUM',
            'SODIUM GLYCEROPHOSPHATE',
            'ZINC CHLORIDE',
            'ZINC GLUCONATE',
            'ZINC SULPHATE',
            'CINACALCET',
            'ETELCALCETIDE',
            'SEVELAMER CARBONATE',
            'SEVELAMER',
            'HYDROCHLORIDE',
            'SUCROFERRIC OXYHYDROXIDE',
            'ALFACALCIDOL',
            'ALPHA TOCOPHEROL',
            'ASCORBIC ACID',
            'BIOTIN',
            'CALCIFEROL',
            'CALCITRIOL',
            'CALCIUM CARBONATE + VITAMIN D',
            'CALPEROS D3 (OR EQUIV)',
            'CHOLECALCIFEROL',
            'DAILY 1 PLUS (OR EQUIV)',
            'ENERVON C (OR EQUIV)',
            'MATERNA (OR EQUIV)',
            'NEPHRONEX (OR EQUIV)',
            'NEUROBION (OR EQUIV)',
            'PHYTOMENADIONE',
            'POLY-VI-SOL (OR EQUIV)',
            'PYRIDOXINE',
            'RIBOFLAVINE',
            'THIAMINE',
            'VITAMIN A',
            'VITAMIN B COMPLEX',
            'PARICALCITOL'
        ];
        $skin = [
            'AQUEOUS CREAM',
            'EMULSIFYING OINTMENT',
            'LIQUID PARAFFIN + WHITE SOFT PARAFFIN',
            'PARAFFIN',
            'UREA',
            'ZINC'
        ];

        $category_items = [
            'GASTRO-INTESTINAL SYSTEM 腸胃科藥物' => $gastro_intestinal_system,
            'CARDIOVASCULAR SYSTEM 心臟科藥物' => $cardiovascular_system,
            'RESPIRATORY SYSTEM 呼吸系統藥物' => $respiratory_system,
            'CENTRAL NERVOUS SYSTEM 中樞神經系統藥物' => $central_nervous_system,
            'NUTRITION AND BLOOD 營養劑及血液科藥物' => $nutritions_and_blood,
            'SKIN 皮膚科藥物' => $skin
        ];

        foreach ($category_items as $category => $items) {
            MedicationDrug::create(
                [
                    'name' => $category,
                    'parent_id' => 0
                ]
            );
        }

        foreach ($category_items as $category => $items) {
            $drug_category_id = MedicationDrug::where('name', $category)->first()->id;

            foreach ($items as $item) {
                MedicationDrug::create(
                    [
                        'name' => $item,
                        'parent_id' => $drug_category_id
                    ]
                );
            }
        }
    }
}
